# <img src="https://img.icons8.com/dusk/64/000000/mind-map.png" style="height:50px;display:inline"> EE 044165/6 - Technion - Intro to Machine Learning Lab

## Part 1 -  Preparation question


###  Get  raw data
The data consisits of 3 text sections.

In [ ]:
texts_raw = ["Here is Edward Bear, coming downstairs now, bump, bump, bump, on the back of his head.", 
         "Sometimes Winnie-the-Pooh likes a game of some sort when he comes downstairs.",
         "Winnie-the-Pooh sat down at the foot of the tree, put his head between his paws and began to think."]
print("\n Raw data: \n", texts_raw)
n_texts = len(texts_raw)


 Raw data: 
 ['Here is Edward Bear, coming downstairs now, bump, bump, bump, on the back of his head.', 'Sometimes Winnie-the-Pooh likes a game of some sort when he comes downstairs.', 'Winnie-the-Pooh sat down at the foot of the tree, put his head between his paws and began to think.']


### Cleaning up
lest's get rid of punctuation characters.

In [ ]:
import string

print('punctuation symbols to be removed: ', string.punctuation)

texts_strings = []

for txt_str in texts_raw:
    # remove punctuations
    for char in string.punctuation:
        txt_str = txt_str.replace(char, ' ')
    texts_strings.append(txt_str)

print('\n Cleaned texts: \n', texts_strings)

punctuation symbols to be removed:  !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

 Cleaned texts: 
 ['Here is Edward Bear  coming downstairs now  bump  bump  bump  on the back of his head ', 'Sometimes Winnie the Pooh likes a game of some sort when he comes downstairs ', 'Winnie the Pooh sat down at the foot of the tree  put his head between his paws and began to think ']


###  Split into words

In [ ]:
texts_words_lists = []

for txt_str in texts_strings:
    # split into words
    texts_words_lists.append(txt_str.split())

print("\n Texts in word list format: \n", texts_words_lists)


 Texts in word list format: 
 [['Here', 'is', 'Edward', 'Bear', 'coming', 'downstairs', 'now', 'bump', 'bump', 'bump', 'on', 'the', 'back', 'of', 'his', 'head'], ['Sometimes', 'Winnie', 'the', 'Pooh', 'likes', 'a', 'game', 'of', 'some', 'sort', 'when', 'he', 'comes', 'downstairs'], ['Winnie', 'the', 'Pooh', 'sat', 'down', 'at', 'the', 'foot', 'of', 'the', 'tree', 'put', 'his', 'head', 'between', 'his', 'paws', 'and', 'began', 'to', 'think']]


###  Create vocabulary dictionary


In [ ]:
from collections import Counter

# concatenate all word lists
all_word_list = sum(texts_words_lists, [])

all_wordCounter = Counter(all_word_list)
print("\n All texts word counter: \n", all_wordCounter)

vocabulary_list = list(all_wordCounter.keys())
print("\n vocabulary list: \n", vocabulary_list)

vocabulary_size = len(vocabulary_list)
print("\n Vocabulary size:", vocabulary_size)


 All texts word counter: 
 Counter({'the': 5, 'bump': 3, 'of': 3, 'his': 3, 'downstairs': 2, 'head': 2, 'Winnie': 2, 'Pooh': 2, 'Here': 1, 'is': 1, 'Edward': 1, 'Bear': 1, 'coming': 1, 'now': 1, 'on': 1, 'back': 1, 'Sometimes': 1, 'likes': 1, 'a': 1, 'game': 1, 'some': 1, 'sort': 1, 'when': 1, 'he': 1, 'comes': 1, 'sat': 1, 'down': 1, 'at': 1, 'foot': 1, 'tree': 1, 'put': 1, 'between': 1, 'paws': 1, 'and': 1, 'began': 1, 'to': 1, 'think': 1})

 vocabulary list: 
 ['Here', 'is', 'Edward', 'Bear', 'coming', 'downstairs', 'now', 'bump', 'on', 'the', 'back', 'of', 'his', 'head', 'Sometimes', 'Winnie', 'Pooh', 'likes', 'a', 'game', 'some', 'sort', 'when', 'he', 'comes', 'sat', 'down', 'at', 'foot', 'tree', 'put', 'between', 'paws', 'and', 'began', 'to', 'think']

 Vocabulary size: 37


###  Create data matrix

In [ ]:
###  Create data matrix
import numpy as np


def create_data_mat(texts_words_lists, vocabulary_list):
    n_texts = len(texts_words_lists)
    vocabulary_size = len(vocabulary_list)
    
    X = np.zeros((n_texts, vocabulary_size), dtype=int)
    
    for i_text in range(n_texts):
        wordCounter = Counter(texts_words_lists[i_text])
        #print('\n wordCounter: \n', wordCounter)
        for i_word in range(vocabulary_size):    
            word = vocabulary_list[i_word]  
           # print('\n word: ', word)
            """
            Your Code Here
            """
            X[i_text, i_word] = wordCounter[word];
         
            
    return X


X = create_data_mat(texts_words_lists, vocabulary_list)
print('\n Data matrix: \n', X)
print('\n Vocabulary list: \n', vocabulary_list)


 Data matrix: 
 [[1 1 1 1 1 1 1 3 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0]
 [0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
  0]
 [0 0 0 0 0 0 0 0 0 3 0 1 2 1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
  1]]

 Vocabulary list: 
 ['Here', 'is', 'Edward', 'Bear', 'coming', 'downstairs', 'now', 'bump', 'on', 'the', 'back', 'of', 'his', 'head', 'Sometimes', 'Winnie', 'Pooh', 'likes', 'a', 'game', 'some', 'sort', 'when', 'he', 'comes', 'sat', 'down', 'at', 'foot', 'tree', 'put', 'between', 'paws', 'and', 'began', 'to', 'think']


###  Pre-process: Threshold
Keep only words that appear at least 3 times in total all texts.

In [ ]:

# Create the new vocabulary word list
vocabulary_list_1 = []
for word in vocabulary_list:
    count = all_wordCounter[word]
    """
    Your Code Here
    """
    if  count > 2:
         vocabulary_list_1.append(word)  

vocabulary_size_1 = len(vocabulary_list_1)

# Create new data matrix:
X_1 = create_data_mat(texts_words_lists, vocabulary_list_1) # Ask to complete this:
    

print('\n Data matrix after threshold pre-process: \n', X_1)
print('\n Vocabulary list 1: \n', vocabulary_list_1)


 Data matrix after threshold pre-process: 
 [[3 1 1 1]
 [0 1 1 0]
 [0 3 1 2]]

 Vocabulary list 1: 
 ['bump', 'the', 'of', 'his']


###  Pre-process: tf-idf  style
Keep only words that appear at least 2 times in total all texts and do not appear in all texts.

Hint:  you can use the numpy functions:  [np.any](https://docs.scipy.org/doc/numpy/reference/generated/numpy.any.html)  or [np.all](https://docs.scipy.org/doc/numpy/reference/generated/numpy.all.html)

In [ ]:

# Create the new vocabulary word list
vocabulary_list_2 = []
for i_word, word in enumerate(vocabulary_list):
    count = all_wordCounter[word]
    # print("\n i_word = ", word)
    """
    Your Code Here
    """
    in_texts = 0
    for i_text in range(n_texts):
      if word in texts_words_lists[i_text]:
        in_texts += 1
    # word_missing = Counter(texts_words_lists[i_text]. [word])
    if count > 1 and in_texts < 3 :
        vocabulary_list_2.append(word)  


vocabulary_size_2 = len(vocabulary_list_2)

# Create new data matrix:
X_2 = create_data_mat(texts_words_lists, vocabulary_list_2) 
    

print('\n Data matrix after tf-idf style pre-process: \n', X_2)
print('\n Vocabulary list 2: \n', vocabulary_list_2)


 Data matrix after tf-idf style pre-process: 
 [[1 3 1 1 0 0]
 [1 0 0 0 1 1]
 [0 0 2 1 1 1]]

 Vocabulary list 2: 
 ['downstairs', 'bump', 'his', 'head', 'Winnie', 'Pooh']


## <img src="https://img.icons8.com/dusk/64/000000/prize.png" style="height:50px;display:inline"> Credits
* Notebook made by Ron Amit (March 2020)
